/*
 Author: Anjani Kumar, IT, 2018
*/

_main(_,__,___){
char *GODS_LAUGH_AT_US="a guy named ANJANI made this....\
?h=hJCLAL^ F+F%%BGBGB+=KBE&j%%BHBFBKB&&o%%BHBFBKB**_*P%%BHBFBKB8!n A%%KGBF EB**_*P\
BHBFBKB**_*P%%BHBFBKB**_*P%%BHBFBKB**_*P%%BGBGB+=KBE&j%%JCLA EB&&o%% h=h\
LAF=F++ABJB&-AHEJCLA%%BPBFCIBABFBCBGBGBEA%% BPBFBAAHBABGBBBHBFBEA%%\
9A&AO?AA4AFA?ABAGBAA4AHBABHBFBEA%%8A&AO?AA4AFA?ACAFBAA4AHBABHBFBEA%%\
+K-AFA3AFA?ADAEBABHBAKGBEA%%==JA=AFA-AFBEADBABHBADNA&AEA%%\
 =I?AA7AFBFA-AFACBABHBABAA7AMBEA%%01JA=AFA-AFBGABBABHBABCA4AKBEA%%\
++I?AA7AFBFA-AHAABABGBBBEBIBEA%%99JA=AFA-AFBICABFA&ACBGBGBEA%%\
 LALAA(AJBAHEBIAALA%%?h=h";_=__++[GODS_LAUGH_AT_US];
a:if((_-->'@')?putchar(++___=='P'?(___/='^')+'\n':!(__&1)?32:124):(_=__++[GODS_LAUGH_AT_US]))goto a;}
main(_____){_____==1&&_main(0,33,0);}
